# Generated by Django 3.0.8 on 2020-07-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200717_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
